# Generated by Django 5.1.3 on 2024-11-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proyect')),
            ],
        ),
    ]
